[package]
name = "gpu_computing"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = "0.19.4"
ocl-interop = "0.1.5"
glium = "0.32.1"
image = "0.24.5"
